### PR TITLE
Update most reference / sepcification URLs

### PR DESCRIPTION
**Pull request by utilum**
Addresses  #232.

Some old links I could not find the new URL for.

### CODE REVIEW

**Comment by utilum** [comment]
The generated doc has some info that the PDF you link to lacks.
For instance, https://github.com/ruby-amqp/amqp/blob/master/lib/amqp/queue.rb#L999:
`# @see http://bit.ly/amqp091reference AMQP 0.9.1 protocol reference (Section 1.7.2.9.)`
But on https://www.rabbitmq.com/resources/specs/amqp0-9-1.pdf Section 1 only goes as far as 1.4.3.

I've now gone over this to make sure that links that mention "Reference" are replaced with links to the generated doc, and links that mention "Specification" replaced with links to the specification URL as you wrote above.

**Comment by michaelklishin** [comment]
@utilum in those cases we should link to the reference, otherwise they are not two versions of the same document.

**Comment by utilum** [comment]
I seem to be missing something. *The* reference?
The HTML page with no numbered sections?
As I could not find another PDF, and did see sections that see to correspond to the code comments in this  [generated doc](https://www.rabbitmq.com/resources/specs/amqp-xml-doc0-9-1.pdf), I've used that...

**Comment by michaelklishin** [comment]
There is a [spec](http://www.rabbitmq.com/resources/specs/amqp0-9-1.pdf) and a [reference produced from protocol's XML file](http://www.rabbitmq.com/resources/specs/amqp-xml-doc0-9-1.pdf) composed for implementers. There is some overlap but they are not the same document.

**Comment by utilum** [comment]
Thank you for clarifying @michaelklishin, I can confirm that this patch substitues 
1) http://files.travis-ci.org/docs/amqp/0.9.1/AMQP091Specification.pdf and http://bit.ly/amqp091reference with https://www.rabbitmq.com/resources/specs/amqp0-9-1.pdf
2) http://files.travis-ci.org/docs/amqp/0.9.1/AMQP091Reference.pdf and http://bit.ly/amqp091reference with https://www.rabbitmq.com/resources/specs/amqp-xml-doc0-9-1.pdf

It does not seem obvious to me from https://www.rabbitmq.com/specification.html, where 1 is referred to as "Specification", and 2 is referred to as "Generated Doc", nor from the linked PDFs. 1 has "Protocol Specification" at the end of its title, and 2 has no title at all, but a footer: "AMQP Specification (XML­derived)".

**Comment by michaelklishin** [comment]
Thank you!

**Pull request merged**
