### PR TITLE
Update channel_id_allocator.rb

### PR DESCRIPTION
**Pull request by ioquatix**
Don't lazy initialize mutex. You may end up with more than one mutex.

### CODE REVIEW

**Comment by ioquatix** [comment]
You might need to change `include AMQP::ChannelIdAllocator` to `prepend AMQP::ChannelIdAllocator`

**Comment by michaelklishin** [comment]
I'd like a little more justification than "you may end up with more than one mutex". This class is not shared across threads and RabbitMQ clients, in general, do not support sharing channels across threads by design.

Also, if the maintainers might need to change something because of your changes, it's on you to make them.

**Comment by michaelklishin** [comment]
OK, so one thing I have missed is that this is a channel ID allocator so it is instantiated by connections, which can be used concurrently.

Is there a specific problem that has led you to discover this?

**Comment by ioquatix** [comment]
Nope, I'm just analyzing ruby code for thread safety issues.

**Comment by ioquatix** [comment]
> I'd like a little more justification than "you may end up with more than one mutex". This class is not shared across threads and RabbitMQ clients, in general, do not support sharing channels across threads by design.

If this is true then you do not need a mutex.

**Comment by ioquatix** [comment]
> Also, if the maintainers might need to change something because of your changes, it's on you to make them in this or dependent PRs.

No, actually it's not.

**Comment by michaelklishin** [comment]
Well, thanks for the recommendation then.

This client used to share channel ID allocator with Bunny. I don't remember the details but Bunny now has its own copy which [does not use lazy initialization](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/session.rb#L1241).

This client is on life support but this looks like a reasonable change and key subset of tests pass (the rest occasionally makes the VM segfault around EventMachine but that's a can of worms we won't touch here).

**Comment by ioquatix** [comment]
Awesome always happy to help :)

**Pull request merged**
